"""
Assembling a standalone script out of three sources:

  1. the RULE  - either lifted verbatim from the library (a saved
     `apply_violation`) or synthesized by the model for a new clause
  2. the HELPERS the rule and harness actually reference, lifted verbatim
     from the library and closed over transitively
  3. the HARNESS  - generated by the model: argparse, main(), the colouring
     calls and the whole .txt report layout

The point of the transitive closure is that the emitted file is genuinely
standalone (`pip install ifcopenshell` and run it anywhere) WITHOUT carrying
the entire helper library along. An A1 script pulls in five short functions;
an A5 script pulls in the space-adjacency graph builder. Nothing else comes
with it.

Source is extracted as TEXT, by line range, rather than round-tripped
through `ast.unparse`  - so comments and formatting survive into the
generated file. A generated script is something a human is expected to read
and put in front of a reviewer; stripping every comment out of it to save
an hour of work here would be a bad trade.
"""
from __future__ import annotations

import ast
import time
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Iterable, Optional

from . import __version__
from .config import (
    MARKER_SIZE_MM, NAME_TAG_TEMPLATE, REPO_ROOT, VIOLATION_PSET, Colour, colour_for,
)

LIBRARY_DIR = REPO_ROOT / "ifcfault" / "library"

# Emission order matters only for module-level constants and class
# definitions; functions resolve at call time. Listed in dependency order so
# the generated file also reads top-down.
HELPER_MODULES = ("contract", "helpers", "edits", "marking")


# ---------------------------------------------------------------------------
# symbol index
# ---------------------------------------------------------------------------
@dataclass
class Symbol:
    name: str
    module: str
    order: int          # position within its module, to preserve source order
    text: str
    referenced: frozenset[str]


def _source_block(lines: list[str], node: ast.AST) -> str:
    """Verbatim source for a top-level node, including its decorators and any
    comment lines sitting directly above it with no blank line in between."""
    start = node.lineno
    decorators = getattr(node, "decorator_list", None)
    if decorators:
        start = min(d.lineno for d in decorators)

    i = start - 2  # 0-based index of the line above `start`
    while i >= 0 and lines[i].lstrip().startswith("#"):
        start = i + 1
        i -= 1

    return "\n".join(lines[start - 1:node.end_lineno])


def _names_in(node: ast.AST) -> frozenset[str]:
    """Every bare name this node reads. Attribute chains (ifcopenshell.guid)
    are ignored  - those resolve through imports, not through the closure."""
    found = set()
    for sub in ast.walk(node):
        if isinstance(sub, ast.Name):
            found.add(sub.id)
    return frozenset(found)


def _absolute_imports(tree: ast.Module, lines: list[str]) -> list[str]:
    """Top-level import statements that survive inlining: absolute ones only.
    Relative imports point at library modules whose contents are being
    inlined, so they must not appear in the generated file."""
    out = []
    for node in tree.body:
        if isinstance(node, ast.Import):
            out.append(_source_block(lines, node))
        elif isinstance(node, ast.ImportFrom):
            if node.level:
                continue  # relative  - resolved by inlining instead
            if node.module == "__future__":
                continue  # emitted once, at the very top
            out.append(_source_block(lines, node))
    return out


def index_module(path: Path, module_label: str) -> tuple[dict[str, Symbol], list[str]]:
    """Every top-level definition and constant in one module, plus its
    absolute imports."""
    source = path.read_text(encoding="utf-8")
    lines = source.splitlines()
    tree = ast.parse(source)

    symbols: dict[str, Symbol] = {}
    for order, node in enumerate(tree.body):
        text = None
        names: list[str] = []

        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names = [node.name]
            text = _source_block(lines, node)
        elif isinstance(node, ast.Assign):
            names = [t.id for t in node.targets if isinstance(t, ast.Name)]
            if names:
                text = _source_block(lines, node)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names = [node.target.id]
            text = _source_block(lines, node)

        if not text or not names:
            continue
        referenced = _names_in(node)
        for name in names:
            symbols[name] = Symbol(name, module_label, order, text, referenced)

    return symbols, _absolute_imports(tree, lines)


def build_index() -> tuple[dict[str, Symbol], list[str]]:
    """The whole helper library, indexed by symbol name."""
    index: dict[str, Symbol] = {}
    imports: list[str] = []
    for module_name in HELPER_MODULES:
        symbols, module_imports = index_module(LIBRARY_DIR / f"{module_name}.py", module_name)
        # A name defined in two modules keeps the FIRST definition, matching
        # the emission order  - helpers is the base layer, marking the top.
        for name, symbol in symbols.items():
            index.setdefault(name, symbol)
        imports.extend(module_imports)
    return index, imports


# ---------------------------------------------------------------------------
# closure
# ---------------------------------------------------------------------------
def closure(seed_names: Iterable[str], index: dict[str, Symbol]) -> list[Symbol]:
    """Every library symbol reachable from `seed_names`, in emission order."""
    wanted: dict[str, Symbol] = {}
    queue = list(seed_names)
    while queue:
        name = queue.pop()
        if name in wanted:
            continue
        symbol = index.get(name)
        if symbol is None:
            continue  # a builtin, an import, or a local  - not ours to inline
        wanted[name] = symbol
        queue.extend(symbol.referenced - wanted.keys())

    module_rank = {m: i for i, m in enumerate(HELPER_MODULES)}
    return sorted(wanted.values(), key=lambda s: (module_rank.get(s.module, 99), s.order))


# ---------------------------------------------------------------------------
# rule extraction
# ---------------------------------------------------------------------------
REQUIRED_RULE_DEFS = ("applicable", "candidates", "apply_violation")
RULE_METADATA_NAMES = ("RULE_ID", "CLAUSE", "DOMAIN", "ELEMENT")


@dataclass
class RuleCode:
    rule_id: str
    clause: str
    domain: str
    element: str
    text: str                    # the rule's own source, ready to inline
    referenced: frozenset[str]   # names it needs from the library
    origin: str                  # human-readable provenance
    #: The rule's own absolute imports (e.g. `from collections import Counter`).
    #: Its relative imports are dropped, since the closure inlines those
    #: targets instead - but an absolute one has no other way into the file.
    imports: tuple[str, ...] = ()


def extract_rule(rule_module: ModuleType) -> RuleCode:
    """Lift a saved rule out of the library as text.

    Everything the module defines at top level is taken  - the three contract
    functions, its metadata constants, its thresholds, and its private
    helpers  - minus the imports, which the closure supplies instead.
    """
    path = Path(rule_module.__file__)
    source = path.read_text(encoding="utf-8")
    lines = source.splitlines()
    tree = ast.parse(source)

    blocks: list[str] = []
    referenced: set[str] = set()
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            continue
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant) \
                and isinstance(node.value.value, str):
            continue  # the module docstring becomes part of the generated header
        blocks.append(_source_block(lines, node))
        referenced |= _names_in(node)

    return RuleCode(
        rule_id=rule_module.RULE_ID,
        clause=rule_module.CLAUSE,
        domain=rule_module.DOMAIN,
        element=getattr(rule_module, "ELEMENT", ""),
        text="\n\n\n".join(blocks),
        referenced=frozenset(referenced),
        origin=f"saved library rule ({Path(rule_module.__file__).name})",
        imports=tuple(_absolute_imports(tree, lines)),
    )


def parse_synthesized_rule(source: str, origin: str) -> RuleCode:
    """Same treatment for a rule the model just wrote: strip its imports,
    keep everything else, and read its metadata out of the AST rather than by
    importing it (which would execute it)."""
    lines = source.splitlines()
    tree = ast.parse(source)

    metadata: dict[str, str] = {}
    blocks: list[str] = []
    referenced: set[str] = set()
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            continue
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant) \
                and isinstance(node.value.value, str):
            continue
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id in RULE_METADATA_NAMES:
                    if isinstance(node.value, ast.Constant):
                        metadata[target.id] = str(node.value.value)
        blocks.append(_source_block(lines, node))
        referenced |= _names_in(node)

    return RuleCode(
        rule_id=metadata.get("RULE_ID", "??"),
        clause=metadata.get("CLAUSE", ""),
        domain=metadata.get("DOMAIN", ""),
        element=metadata.get("ELEMENT", ""),
        text="\n\n\n".join(blocks),
        referenced=frozenset(referenced),
        origin=origin,
        imports=tuple(_absolute_imports(tree, lines)),
    )


# ---------------------------------------------------------------------------
# assembly
# ---------------------------------------------------------------------------
BANNER = "# " + "=" * 76


def _section(title: str, note: str = "") -> str:
    out = [BANNER, f"# {title}"]
    if note:
        for line in note.strip().splitlines():
            out.append(f"# {line}".rstrip())
    out.append(BANNER)
    return "\n".join(out)


def _py_repr(value) -> str:
    return repr(value)


def build_config_block(*, source_ifc: Path, output_stem: str, rule: RuleCode,
                       colour: Colour, model_name: str, harness_origin: str) -> str:
    """The constants the harness is allowed to rely on. Emitting these as
    plain module-level names (rather than making the harness parse anything)
    is what keeps the generated harness short enough for a 32B model to get
    right."""
    lines = [
        _section("CONFIGURATION",
                 "Generated values. Edit these if you move the file or want a\n"
                 "different default output location; nothing else needs changing."),
        "",
        f"SOURCE_IFC = {_py_repr(str(source_ifc))}",
        f"OUTPUT_STEM = {_py_repr(output_stem)}",
        "",
        f"RULE_ID = {_py_repr(rule.rule_id)}",
        f"RULE_CLAUSE = {_py_repr(rule.clause)}",
        f"RULE_DOMAIN = {_py_repr(rule.domain)}",
        f"RULE_ELEMENT = {_py_repr(rule.element)}",
        f"RULE_ORIGIN = {_py_repr(rule.origin)}",
        "",
        "#: True when this rule REMOVES elements, so the violating element no",
        "#: longer exists to colour and only a marker box can point at it.",
        f"RULE_DELETES_ELEMENTS = {_py_repr(rule.rule_id in ('S4', 'S5'))}",
        "#: True when the mutation's target GlobalId is a storey rather than a",
        "#: single element (S5 empties a whole storey).",
        f"TARGET_IS_A_STOREY = {_py_repr(rule.rule_id == 'S5')}",
        "",
        f"COLOUR_NAME = {_py_repr(colour.name)}",
        f"COLOUR_HEX = {_py_repr(colour.hex)}",
        f"COLOUR_RGB = {_py_repr(colour.rgb)}",
        "",
        f"NAME_TAG_PREFIX = {_py_repr(NAME_TAG_TEMPLATE.format(rule_id=rule.rule_id))}",
        f"VIOLATION_PSET = {_py_repr(VIOLATION_PSET)}",
        f"MARKER_SIZE_MM = {_py_repr(MARKER_SIZE_MM)}",
        "",
        f"GENERATOR_VERSION = {_py_repr(__version__)}",
        f"HARNESS_GENERATED_BY = {_py_repr(model_name)}",
        f"HARNESS_ORIGIN = {_py_repr(harness_origin)}",
        f"SCRIPT_GENERATED_AT = {_py_repr(time.strftime('%Y-%m-%dT%H:%M:%S'))}",
        "",
        "#: Fixed colour table, reproduced here so the report is self-contained.",
        "COLOUR_LEGEND = [",
    ]
    from .config import COLOURS

    for rule_id, entry in COLOURS.items():
        lines.append(f"    ({rule_id!r}, {entry.name!r}, {entry.hex!r}),")
    lines.append("]")
    return "\n".join(lines)


def build_header(*, source_ifc: Path, rule: RuleCode, colour: Colour,
                 model_name: str, output_stem: str) -> str:
    return '\n'.join([
        "#!/usr/bin/env python3",
        '"""',
        f"Injects a single {rule.rule_id} compliance violation into an IFC model.",
        "",
        "  Rule    : " + f"{rule.rule_id}  - {rule.clause}",
        "  Target  : " + (rule.element or "(see the rule below)"),
        "  Source  : " + str(source_ifc),
        "  Colour  : " + colour.describe(),
        "",
        "Running this script writes four files next to each other:",
        "",
        f"  {output_stem}.ifc            the faulty model, with NO visual marking  - ",
        "                               use this one to test a compliance checker,",
        "                               since colouring it would hand the checker",
        "                               the answer",
        f"  {output_stem}_colored.ifc    the same faults, marked up for a human:",
        "                               coloured, name-tagged, with a marker box  - ",
        "                               open this one in Revit or an IFC viewer",
        f"  {output_stem}_report.txt     what was changed, where, and how to find it",
        f"  {output_stem}_record.json    the same facts, machine-readable, for auditing",
        "",
        "HOW THIS FILE WAS BUILT",
        "",
        "  " + f"rule logic  : {rule.origin}",
        "  " + f"harness     : generated by {model_name}",
        "  " + "helpers     : inlined verbatim from the ifcfault library, closed over",
        "                transitively  - this file has no dependency beyond ifcopenshell",
        "",
        "It is deterministic: the target is chosen by a ranked, tie-broken-by-GlobalId",
        "score, and every entity it creates gets a hash-derived GlobalId, so running it",
        "twice on the same input produces byte-identical output.",
        '"""',
        "from __future__ import annotations",
    ])


def assemble(*, rule: RuleCode, harness_source: str, source_ifc: Path, output_stem: str,
             model_name: str, harness_origin: str,
             colour: Optional[Colour] = None) -> str:
    """Stitch the final script together."""
    colour = colour or colour_for(rule.rule_id)
    index, library_imports = build_index()

    # The closure is seeded from BOTH the rule and the harness, since the
    # harness calls library primitives (paint_element, sha256_of, ...) too.
    harness_names = _names_in(ast.parse(harness_source))
    symbols = closure(set(rule.referenced) | set(harness_names), index)

    # Only keep imports from modules that actually contributed something,
    # then dedupe while preserving order.
    contributing = {s.module for s in symbols}
    kept_imports: list[str] = []
    seen: set[str] = set()
    for module_name in HELPER_MODULES:
        if module_name not in contributing:
            continue
        _, module_imports = index_module(LIBRARY_DIR / f"{module_name}.py", module_name)
        for statement in module_imports:
            if statement not in seen:
                seen.add(statement)
                kept_imports.append(statement)
    # The rule's own absolute imports (collections.Counter, math, ...) have no
    # other route into the generated file, so they go in too.
    for statement in rule.imports:
        if statement not in seen:
            seen.add(statement)
            kept_imports.append(statement)
    # The harness needs its own imports; those arrive inside harness_source.

    parts = [
        build_header(source_ifc=source_ifc, rule=rule, colour=colour,
                     model_name=model_name, output_stem=output_stem),
        "",
        _section("IMPORTS"),
        "\n".join(kept_imports) if kept_imports else "import ifcopenshell",
        "",
        build_config_block(source_ifc=source_ifc, output_stem=output_stem, rule=rule,
                           colour=colour, model_name=model_name,
                           harness_origin=harness_origin),
        "",
        _section(
            "INLINED LIBRARY",
            "Lifted verbatim from ifcfault/library/. Not generated code  - this is\n"
            "the reviewed helper layer, copied in so the script stands alone.\n"
            f"{len(symbols)} symbol(s) from: " + ", ".join(sorted(contributing)),
        ),
        "\n\n\n".join(s.text for s in symbols),
        "",
        _section(
            f"RULE {rule.rule_id}",
            rule.origin + "\n" + rule.clause,
        ),
        rule.text,
        "",
        _section(
            "HARNESS",
            f"Generated by {model_name}.\n"
            "Validated before this file was written: static safety gate, then\n"
            "executed against the real source model, then the result checked by an\n"
            "independent verifier that shares no code with the rule above.",
        ),
        harness_source.strip(),
        "",
        "",
        'if __name__ == "__main__":',
        "    raise SystemExit(main())",
        "",
    ]
    return "\n".join(parts)
